server:
  port: 9999
spring:
  application:
    name: robin-eureka
  #security:
   # user:
    ###  name: robin
    #  password: 123456
eureka:
  instance:
    hostname: 192.168.0.61
  client:
    register-with-eureka: false     # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: false  # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
  server:
    enable-self-preservation: false
